name: Build Docker Image

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker image
        run: |
          docker build --no-cache -t kaelsong-api:latest .
          
      - name: Save image to tar
        run: |
          docker save -o kaelsong-api.tar kaelsong-api:latest
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: kaelsong-api-image
          path: kaelsong-api.tar